apiVersion: v1
kind: Pod
metadata:
  name: avg-speed-latvia
  labels:
    app: avg-speed-latvia
    version: v1
spec:
  containers:
    - name: avg-speed-latvia
      image: amirdirin/lectdemo2026_latvia_devops:v1
      imagePullPolicy: Always
      stdin: true
      tty: true
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "200m"